export const NLP_MODEL_REQ = 'NLP_MODEL_REQ'
export const NLP_MODEL_SUCCESS = 'NLP_MODEL_SUCCESS'
export const NLP_MODEL_FAILURE = 'NLP_MODEL_FAILURE'

export const NLP_ANSWER_REQ = 'NLP_ANSWER_REQ'
export const NLP_ANSWER_SUCCESS = 'NLP_ANSWER_SUCCESS'
export const NLP_ANSWER_FAILURE = 'NLP_ANSWER_FAILURE'

export const COCO_MODEL_REQ = 'COCO_MODEL_REQ'
export const COCO_MODEL_SUCCESS = 'COCO_MODEL_SUCCESS'
export const COCO_MODEL_FAILURE = 'COCO_MODEL_FAILURE'

export const COCO_PREDICTION_REQ = 'COCO_PREDICTION_REQ'
export const COCO_PREDICTION_SUCCESS = 'COCO_PREDICTION_SUCCESS'
export const COCO_PREDICTION_FAILURE = 'COCO_PREDICTION_FAILURE'